import Head from "next/head";
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiFillGithub,
  AiFillChrome,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import jaco from "../public/images/Jaco3.png";
import html from "../public/images/html.png";
import css from "../public/images/css.png";
import javascript from "../public/images/javascript.png";
import bootstrap from "../public/images/Boostrap.png";
import node from "../public/images/node.png";
import react from "../public/images/react.png";
import next from "../public/images/next.png";
import mui from "../public/images/MUI.png";
import tailwind from "../public/images/tailwind.png";
import firebase from "../public/images/firebase.png";
import Image from "next/image";
import slidedepot from "../public/images/slidedepot.png";
import dorshs from "../public/images/Dorshs.png";
import nf from "../public/images/nf-clone.png";
import driff from "../public/images/driff.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jaco Raven Miras - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">jacoravenmiras</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Jaco Raven Miras
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Frontend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a web developer with extensive knowledge on front-end
              development. I love solving problems and I view coding as my
              passion. I am confident on my ability to learn and on to work
              under pressure.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.facebook.com/jraven.miras">
                <AiFillFacebook />
              </a>
              <a href="https://www.linkedin.com/in/jaco-raven-miras-13b6aa201/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Jaco-Miras">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={jaco} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Skills</h3>
          </div>
          <div className="w-full grid grid-cols-2 sm:grid-cols-4 gap-4 text-center py-20 px-5 mx-auto">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={html} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Html</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={css} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">CSS</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={javascript} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Javascript</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={bootstrap} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Bootstrap</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={node} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">NodeJS</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={react} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">ReactJs</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={next} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">NextJs</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={mui} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">MUI</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={tailwind} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Tailwind</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={firebase} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Firebase</h3>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <p>Driff</p>
              <div className="mt-2 flex gap-4">
                <a
                  href="https://driff.io/"
                  className="bg-[#F49D1A] px-4 py-2 rounded flex items-center gap-2 "
                >
                  <AiFillChrome />
                  View Website
                </a>
                {/* 
                <a
                  href="https://github.com/tactivstudios/slidedepot"
                  className="bg-[#333] px-4 py-2 rounded flex items-center gap-2 text-white"
                >
                  <AiFillGithub />
                  Github
                </a> */}
              </div>
              <Image
                className="rounded-lg"
                width={"90%"}
                height={"50%"}
                layout="responsive"
                src={driff}
              />
            </div>

            <div className="basis-1/3 flex-1">
              <p className="">DORSHS</p>
              <div className="mt-2 flex gap-4">
                <a
                  href="https://dorshs.com/"
                  className="bg-[#F49D1A] px-4 py-2 rounded flex items-center gap-2 "
                >
                  <AiFillChrome />
                  View Website
                </a>

                <a
                  href="https://github.com/Jaco-Miras/dorshs"
                  className="bg-[#333] px-4 py-2 rounded flex items-center gap-2 text-white"
                >
                  <AiFillGithub />
                  Github
                </a>
              </div>
              <Image
                className="rounded "
                width={"90%"}
                height={"50%"}
                layout="responsive"
                src={dorshs}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <p className="">Netflix-Clone</p>
              <div className="mt-2 flex gap-4">
                <a
                  href="https://netflix-clone-tawny-rho.vercel.app/"
                  className="bg-[#F49D1A] px-4 py-2 rounded flex items-center gap-2"
                >
                  <AiFillChrome />
                  View Website
                </a>

                <a
                  href="https://github.com/Jaco-Miras/nf"
                  className="bg-[#333] px-4 py-2 rounded flex items-center gap-2 text-white"
                >
                  <AiFillGithub />
                  Github
                </a>
              </div>
              <Image
                className="rounded "
                width={"90%"}
                height={"50%"}
                layout="responsive"
                src={nf}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <p className="">Slide Depot</p>
              <div className="mt-2 flex gap-4">
                {/* <a
                  href="https://netflix-clone-tawny-rho.vercel.app/"
                  className="bg-[#F49D1A] px-4 py-2 rounded flex items-center gap-2"
                >
                  <AiFillChrome />
                  View Website
                </a> */}

                <a
                  href="https://github.com/tactivstudios/slidedepot"
                  className="bg-[#333] px-4 py-2 rounded flex items-center gap-2 text-white"
                >
                  <AiFillGithub />
                  Github
                </a>
              </div>
              <Image
                className="rounded "
                width={"90%"}
                height={"50%"}
                layout="responsive"
                src={slidedepot}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
